// Generated by FlutterFire CLI — do not edit manually.
// Project: cmcda-2f485 | Platforms: Android, Web
// Last updated: 2026-05-04

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS is not a supported platform for CMCDA.');
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not a supported platform for CMCDA.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not a supported platform for CMCDA.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not a supported platform for CMCDA.');
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIzwDfhjHVWliqz_A5mwUGu-s_wEChZ0',
    appId: '1:1050677298259:android:32194dc79392bcdbb5b2a6',
    messagingSenderId: '1050677298259',
    projectId: 'cmcda-2f485',
    storageBucket: 'cmcda-2f485.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsnEh6ssF8HHnVSzvKLCGFMFjbfQvUiSU',
    appId: '1:1050677298259:web:c27ea1b120af8c78b5b2a6',
    messagingSenderId: '1050677298259',
    projectId: 'cmcda-2f485',
    authDomain: 'cmcda-2f485.firebaseapp.com',
    storageBucket: 'cmcda-2f485.firebasestorage.app',
    measurementId: 'G-CWSLTXFR6E',
  );
}
